/**
* @Author: yanKoo
* @Date: 2019/3/11 10:39
* @Description: main api file url: https://127.0.0.1:10000/swagger/index.html
 */
package main

import (
	_ "net/http/pprof"
	_ "web-api/docs" // docs is generated by Swag CLI,
	"web-api/runner"
)

// @title JiMi Web API
// @version 1.0.1
// @description jimi co ptt platform web api.
func main() {
	runner.NewWebServerRunner().Run()
}
