// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-06-24 09:52:11.772174 +0800 CST m=+0.482027601

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "jimi co ptt platform web api.",
        "title": "JiMi Web API",
        "contact": {},
        "license": {},
        "version": "1.0.1"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "创建下级账户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建下级账户所用的信息，role_id只能是2、3、4， 低等级不能创建等级高的用户",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagCreateAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "操作成功会返回的json内容",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagCreateAccountResp"
                        }
                    }
                }
            }
        },
        "/account/info/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新下级账户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新下级账户的信息，其中id和loginId和NickName不能为空",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagAccountUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新下级账户成功应该返回的信息",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagAccountUpdateResp"
                        }
                    }
                }
            }
        },
        "/account/login.do/{account_name}": {
            "post": {
                "description": "login by account name and pwd",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录的用户名，eg：elephant",
                        "name": "account_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "登录信息，username和pwd必填",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AccountForSwag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"session_id\": \"1c2c46b8-f44a-4073-b219-d93d22dd2a43\", \"success\": \"true\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account/logout.do/{account_name}": {
            "post": {
                "description": "logout by account name and pwd, 请求头中Authorization参数设置为登录时返回的sessionId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "退出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId eg:1c2c46b8-f44a-4073-b219-d93d22dd2a43",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "登录信息，username和pwd必填",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AccountForSwag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":\"true\",\"msg\": \"SignOut is successful\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account/pwd/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新用户密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新用户密码",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagAccountPwd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正确处理返回的数据",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagAccountPwdResp"
                        }
                    }
                }
            }
        },
        "/account/{account_name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取账户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前用户的账号",
                        "name": "account_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正确操作应该返回的数据",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagGetAccountInfoResp"
                        }
                    }
                }
            }
        },
        "/account_class/{accountId}/{searchId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取账户下级目录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "获取用户下级目录的账号Id",
                        "name": "searchId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正确处理返回的数据",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagGetAccountClassResp"
                        }
                    }
                }
            }
        },
        "/account_delete/{accountId}/{deleteId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "删除账户下级用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "删除用户下级的账号Id",
                        "name": "deleteId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "\t{\"msg\":\"delete account successfully.\",\"result\": \"success\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/account_device/{accountId}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "转移设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "转移设备的model",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagAccountDeviceTransReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "处理正确返回的数据",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagTransAccountDeviceResp"
                        }
                    }
                }
            }
        },
        "/account_device/{accountId}/{getAdviceId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取账户的设备信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "获取用户设备信息的账号Id",
                        "name": "getAdviceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正确处理返回的数据",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagGetAccountDeviceResp"
                        }
                    }
                }
            }
        },
        "/account_device_gps/{accountId}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取账户的某些设备gps信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "获取设备的model",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagDeviceInfosReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正确处理返回的数据",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagGetDeviceLocationResp"
                        }
                    }
                }
            }
        },
        "/device/import/{account_name}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "导入设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前用户的账号",
                        "name": "account_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "导入设备的model",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagAccountImportDeviceReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "处理正确返回的数据",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagImportDeviceByRootResp"
                        }
                    }
                }
            }
        },
        "/device/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "更新设备信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前用户的账号",
                        "name": "account_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "处理正确返回的数据",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagUpdateDeviceInfoResp"
                        }
                    }
                }
            }
        },
        "/group": {
            "post": {
                "description": "web创建群组, 请求头中Authorization参数设置为登录时返回的sessionId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web创建群组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建群组",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.GroupList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":\"true\",\"msg\": resUpd.ResultMsg.Msg}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/group/delete": {
            "post": {
                "description": "web创建群组, 请求头中Authorization参数设置为登录时返回的sessionId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web群组删除，目前只更新群组名字",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "web更新群组",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.GroupInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":\"true\",\"msg\": resUpd.ResultMsg.Msg}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/group/devices/update": {
            "post": {
                "description": "logout by account name and pwd, 请求头中Authorization参数设置为登录时返回的sessionId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web更新群组中的设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新群组中的设备",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.GroupList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":\"true\",\"msg\": resUpd.ResultMsg.Msg}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/group/update": {
            "post": {
                "description": "web创建群组, 请求头中Authorization参数设置为登录时返回的sessionId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web更新群组信息，目前只更新群组名字",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "web更新群组",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.GroupInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":\"true\",\"msg\": resUpd.ResultMsg.Msg}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/group_manager/update": {
            "post": {
                "description": "web更新群组成员是否为管理员, 请求头中Authorization参数设置为登录时返回的sessionId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web更新群组成员是否为管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "web更新群组管理员body内容，注意 RoleType 只能为1或者2， 2是指修改为管理员，1是指修改为普通成员",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagUpdGManagerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":\"true\",\"msg\": resUpd.ResultMsg.Msg}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/im-server/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "websocket与grpc交换数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"User information obtained successfully\",\t\"account_info\": ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "model.ImMsgData",
                        "description": "上传文件携带的参数",
                        "name": "fileInfo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\":\"User information obtained successfully\",\t\"account_info\": ai,\t\"device_list\" deviceAll,\"group_list\": gList,\"tree_data\":resp}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/wifi/{accountId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取wifi信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "\t{\"msg\":\"delete account successfully.\",\"result\": \"success\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "增加，删除，修改wifi信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录时返回的sessionId",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "当前用户的账号Id",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "获取wifi的model",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagWifiInfoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正确处理返回的数据",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SwagGetDeviceLocationResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Account": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "c_time": {
                    "type": "string"
                },
                "change_time": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ll_time": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                },
                "privilege_id": {
                    "type": "integer"
                },
                "pwd": {
                    "type": "string",
                    "example": "123456"
                },
                "remark": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "elephant"
                }
            }
        },
        "model.AccountClass": {
            "type": "object",
            "properties": {
                "account_name": {
                    "type": "string"
                },
                "account_nickname": {
                    "type": "string"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AccountClass"
                    }
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "model.AccountForSwag": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "pwd": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "elephant"
                }
            }
        },
        "model.Device": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "active_time": {
                    "type": "string"
                },
                "change_time": {
                    "type": "string"
                },
                "course": {
                    "type": "number"
                },
                "create_time": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "gps_data": {
                    "type": "object",
                    "$ref": "#/definitions/model.GPS"
                },
                "id": {
                    "type": "integer"
                },
                "imei": {
                    "type": "string"
                },
                "last_login_time": {
                    "type": "string"
                },
                "local_time": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "online": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "sale_time": {
                    "type": "string"
                },
                "speed": {
                    "type": "number"
                },
                "user_name": {
                    "type": "string"
                },
                "wifi_des": {
                    "type": "string"
                }
            }
        },
        "model.DeviceReceiver": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "account_name": {
                    "type": "string"
                }
            }
        },
        "model.GPS": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                }
            }
        },
        "model.GroupInfo": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "c_time": {
                    "type": "string"
                },
                "group_manager": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "group_name": {
                    "type": "string"
                },
                "group_owner": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "online_num": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.GroupList": {
            "type": "object",
            "properties": {
                "device_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "device_infos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.User"
                    }
                },
                "group_info": {
                    "type": "object",
                    "$ref": "#/definitions/model.GroupInfo"
                }
            }
        },
        "model.SwagAccount": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "c_time": {
                    "type": "string"
                },
                "change_time": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ll_time": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                },
                "privilege_id": {
                    "type": "integer"
                },
                "pwd": {
                    "type": "string",
                    "example": "123456"
                },
                "remark": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "elephant"
                }
            }
        },
        "model.SwagAccountDeviceTransReq": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SwagDevice"
                    }
                },
                "receiver": {
                    "type": "object",
                    "$ref": "#/definitions/model.DeviceReceiver"
                },
                "sender": {
                    "type": "object",
                    "$ref": "#/definitions/model.SwagAccount"
                }
            }
        },
        "model.SwagAccountImportDeviceReq": {
            "type": "object",
            "properties": {
                "d_type": {
                    "type": "string"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SwagImportDevice"
                    }
                }
            }
        },
        "model.SwagAccountPwd": {
            "type": "object",
            "required": [
                "confirm_pwd",
                "id",
                "new_pwd",
                "old_pwd"
            ],
            "properties": {
                "confirm_pwd": {
                    "type": "string",
                    "example": "123456"
                },
                "id": {
                    "type": "string",
                    "example": "10"
                },
                "new_pwd": {
                    "type": "string",
                    "example": "123123"
                },
                "old_pwd": {
                    "type": "string",
                    "example": "111111"
                }
            }
        },
        "model.SwagAccountPwdResp": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string",
                    "example": "Password changed successfully"
                },
                "result": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.SwagAccountUpdate": {
            "type": "object",
            "required": [
                "id",
                "login_id",
                "nick_name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "123456789@qq.com"
                },
                "id": {
                    "type": "string",
                    "example": "170"
                },
                "login_id": {
                    "type": "string",
                    "example": "10"
                },
                "nick_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string",
                    "example": "12345671234"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "model.SwagAccountUpdateResp": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string",
                    "example": "update account success"
                },
                "result": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.SwagCreateAccount": {
            "type": "object",
            "required": [
                "confirm_pwd",
                "nick_name",
                "pid",
                "pwd",
                "role_id",
                "username"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "confirm_pwd": {
                    "type": "string",
                    "example": "123456"
                },
                "contact": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "123456789@qq.com"
                },
                "nick_name": {
                    "type": "string",
                    "example": "nickDis001"
                },
                "phone": {
                    "type": "string",
                    "example": "12345678455"
                },
                "pid": {
                    "type": "integer",
                    "example": 13
                },
                "pwd": {
                    "type": "string",
                    "example": "123456"
                },
                "remark": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer",
                    "example": 2
                },
                "username": {
                    "type": "string",
                    "example": "disks007"
                }
            }
        },
        "model.SwagCreateAccountResp": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string",
                    "example": "666"
                },
                "result": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.SwagDevice": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "active_time": {
                    "type": "string"
                },
                "change_time": {
                    "type": "string"
                },
                "course": {
                    "type": "number"
                },
                "create_time": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "gps_data": {
                    "type": "object",
                    "$ref": "#/definitions/model.GPS"
                },
                "id": {
                    "type": "integer"
                },
                "imei": {
                    "type": "string"
                },
                "last_login_time": {
                    "type": "string"
                },
                "local_time": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "sale_time": {
                    "type": "string"
                },
                "speed": {
                    "type": "number"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "model.SwagDeviceInfo": {
            "type": "object",
            "properties": {
                "AccountId": {
                    "type": "integer"
                },
                "ActiveTime": {
                    "type": "string"
                },
                "ChangeTime": {
                    "type": "string"
                },
                "CreateTime": {
                    "type": "string"
                },
                "DeviceType": {
                    "type": "string"
                },
                "IMei": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "LLTime": {
                    "type": "string"
                },
                "NickName": {
                    "type": "string"
                },
                "PassWord": {
                    "type": "string"
                },
                "SaleTime": {
                    "type": "string"
                },
                "UserName": {
                    "type": "string"
                },
                "battery": {
                    "type": "integer"
                },
                "course": {
                    "type": "number"
                },
                "latitude": {
                    "type": "number"
                },
                "localTime": {
                    "type": "integer"
                },
                "longitude": {
                    "type": "number"
                },
                "speed": {
                    "type": "number"
                }
            }
        },
        "model.SwagDeviceInfosReq": {
            "type": "object",
            "properties": {
                "DevicesIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        2
                    ]
                }
            }
        },
        "model.SwagGetAccountClassResp": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string",
                    "example": "success"
                },
                "tree_data": {
                    "type": "object",
                    "$ref": "#/definitions/model.AccountClass"
                }
            }
        },
        "model.SwagGetAccountDeviceResp": {
            "type": "object",
            "properties": {
                "account_info": {
                    "type": "object",
                    "$ref": "#/definitions/model.Account"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Device"
                    }
                }
            }
        },
        "model.SwagGetAccountInfoResp": {
            "type": "object",
            "properties": {
                "account_info": {
                    "type": "string"
                },
                "device_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Device"
                    }
                },
                "group_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.GroupList"
                    }
                },
                "tree_data": {
                    "type": "object",
                    "$ref": "#/definitions/model.AccountClass"
                }
            }
        },
        "model.SwagGetDeviceLocationResp": {
            "type": "object",
            "properties": {
                "Devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SwagDeviceInfo"
                    }
                }
            }
        },
        "model.SwagImportDevice": {
            "type": "object",
            "required": [
                "active_time",
                "device_type",
                "id",
                "imei",
                "sale_time"
            ],
            "properties": {
                "active_time": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imei": {
                    "type": "string"
                },
                "sale_time": {
                    "type": "string"
                }
            }
        },
        "model.SwagImportDeviceByRootResp": {
            "type": "object",
            "properties": {
                "duli_devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SwagDevice"
                    }
                },
                "err_devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SwagDevice"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "model.SwagTransAccountDeviceResp": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string",
                    "example": "trans successful"
                },
                "result": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.SwagUpdGManagerReq": {
            "type": "object",
            "properties": {
                "AccountId": {
                    "type": "integer",
                    "example": 10
                },
                "GId": {
                    "type": "integer",
                    "example": 2
                },
                "RoleType": {
                    "type": "integer",
                    "example": 2
                },
                "UId": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        8
                    ]
                }
            }
        },
        "model.SwagUpdateDeviceInfoResp": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string",
                    "example": "update device info successfully"
                }
            }
        },
        "model.SwagWifi": {
            "type": "object",
            "properties": {
                "bss_id": {
                    "type": "string"
                },
                "des": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "level": {
                    "type": "integer"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "model.SwagWifiInfoReq": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "integer"
                },
                "ops": {
                    "type": "integer"
                },
                "wifis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SwagWifi"
                    }
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "account_id": {
                    "description": "只有普通用户才有这个字段，表示这个设备属于哪个账户，如果是非普通用户就是默认为0（因为customer表里面没有0号）",
                    "type": "integer"
                },
                "active_time": {
                    "type": "string"
                },
                "change_time": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "group_type": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "imei": {
                    "type": "string"
                },
                "last_login_time": {
                    "type": "string"
                },
                "lock_group_id": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "online": {
                    "type": "integer"
                },
                "parent_id": {
                    "description": "如果是普通APP用户和设备注册的时候，默认是0， 如果是上级用户创建下级账户，就用来表示创建者的id",
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "sale_time": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_type": {
                    "description": "用户类型(暂定1是普通用户，2是调度员，3是经销商, 4是超级管理员)",
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
